package ui;

/***
 * A JDialog showing a description of the application and its authors.
 */
public class AboutDialog extends javax.swing.JDialog {

    /** Creates new form AboutDialog */
    public AboutDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextArea7 = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea6 = new javax.swing.JTextArea();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextArea8 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);
        setResizable(false);
        getContentPane().setLayout(new java.awt.BorderLayout(10, 10));

        jLabel1.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sobre");
        getContentPane().add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jTextArea2.setEditable(false);
        jTextArea2.setText("Primeira versão do programa para reordenação de textos. \n\nSolicitado pelo professor André Angelis, mostrado abaixo, e realizado pelo Grupo 4, \ncujos integrantes estão descritos abaixo.   \n\nRefere-se à uma atividade da disciplina SI400 - Programação Orientada a Objetos II. \nProjeto realizado em Outubro de 2022 na Universidade Estadual de Campinas - UNICAMP.");
        jTextArea2.setFocusable(false);
        jScrollPane2.setViewportView(jTextArea2);

        getContentPane().add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel1.setLayout(new java.awt.GridLayout(3, 0));

        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/imgs/AlvaroCosta.png"))); // NOI18N
        jPanel2.add(jLabel2);

        jTextArea4.setEditable(false);
        jTextArea4.setRows(2);
        jTextArea4.setText("Álvaro Augusto Costa\n246909");
        jTextArea4.setPreferredSize(new java.awt.Dimension(175, 36));
        jScrollPane4.setViewportView(jTextArea4);

        jPanel2.add(jScrollPane4);

        jPanel1.add(jPanel2);

        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/imgs/LuizaRehbein.png"))); // NOI18N
        jPanel3.add(jLabel3);

        jTextArea3.setEditable(false);
        jTextArea3.setRows(2);
        jTextArea3.setText("Luiza Tirelli Rehbein\n254303");
        jTextArea3.setPreferredSize(new java.awt.Dimension(175, 36));
        jScrollPane3.setViewportView(jTextArea3);

        jPanel3.add(jScrollPane3);

        jPanel1.add(jPanel3);

        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/imgs/BrunoDiniz.png"))); // NOI18N
        jPanel4.add(jLabel4);

        jTextArea5.setEditable(false);
        jTextArea5.setRows(2);
        jTextArea5.setText("Bruno Diniz Ferrarezzo \n254178");
        jTextArea5.setPreferredSize(new java.awt.Dimension(175, 36));
        jScrollPane5.setViewportView(jTextArea5);

        jPanel4.add(jScrollPane5);

        jPanel1.add(jPanel4);

        jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/imgs/MarceloDrumond.png"))); // NOI18N
        jPanel6.add(jLabel6);

        jTextArea7.setEditable(false);
        jTextArea7.setRows(2);
        jTextArea7.setText("Marcelo Teixeira Drumond\n254308");
        jTextArea7.setPreferredSize(new java.awt.Dimension(175, 36));
        jScrollPane7.setViewportView(jTextArea7);

        jPanel6.add(jScrollPane7);

        jPanel1.add(jPanel6);

        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/imgs/GabrielFernandes.png"))); // NOI18N
        jPanel5.add(jLabel5);

        jTextArea6.setEditable(false);
        jTextArea6.setRows(2);
        jTextArea6.setText("Gabriel Fernandes Silva\n247106");
        jTextArea6.setPreferredSize(new java.awt.Dimension(175, 36));
        jScrollPane6.setViewportView(jTextArea6);

        jPanel5.add(jScrollPane6);

        jPanel1.add(jPanel5);

        jPanel7.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/imgs/AndreAngelis.png"))); // NOI18N
        jPanel7.add(jLabel7);

        jTextArea8.setEditable(false);
        jTextArea8.setRows(2);
        jTextArea8.setText("Prof. Dr. André Franceschi\nde Angelis");
        jTextArea8.setPreferredSize(new java.awt.Dimension(175, 36));
        jScrollPane8.setViewportView(jTextArea8);

        jPanel7.add(jScrollPane8);

        jPanel1.add(jPanel7);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JTextArea jTextArea6;
    private javax.swing.JTextArea jTextArea7;
    private javax.swing.JTextArea jTextArea8;
    // End of variables declaration//GEN-END:variables

}
